spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # Recria as tabelas ao iniciar a aplicação
    show-sql: true
  sql:
    init:
      mode: always # Garante que o script data.sql seja executado
